set(_CATKIN_CURRENT_PACKAGE "teletouch_pkg")
set(teletouch_pkg_VERSION "0.0.0")
set(teletouch_pkg_MAINTAINER "xiaohulu1130 <xiaohulu1130@todo.todo>")
set(teletouch_pkg_PACKAGE_FORMAT "2")
set(teletouch_pkg_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "touch_custom_msgs" "omni_description" "omni_msgs" "tf" "xacro")
set(teletouch_pkg_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "omni_description" "omni_msgs" "tf" "xacro")
set(teletouch_pkg_BUILDTOOL_DEPENDS "catkin")
set(teletouch_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(teletouch_pkg_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "touch_custom_msgs" "omni_description" "omni_msgs" "tf" "xacro")
set(teletouch_pkg_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "touch_custom_msgs" "omni_description" "omni_msgs" "tf" "xacro")
set(teletouch_pkg_TEST_DEPENDS )
set(teletouch_pkg_DOC_DEPENDS )
set(teletouch_pkg_URL_WEBSITE "")
set(teletouch_pkg_URL_BUGTRACKER "")
set(teletouch_pkg_URL_REPOSITORY "")
set(teletouch_pkg_DEPRECATED "")