set(_CATKIN_CURRENT_PACKAGE "yumi_startup")
set(yumi_startup_VERSION "0.0.1")
set(yumi_startup_MAINTAINER "Frederick Wachter <wachterfreddy@gmail.com>")
set(yumi_startup_PACKAGE_FORMAT "1")
set(yumi_startup_BUILD_DEPENDS )
set(yumi_startup_BUILD_EXPORT_DEPENDS )
set(yumi_startup_BUILDTOOL_DEPENDS "catkin")
set(yumi_startup_BUILDTOOL_EXPORT_DEPENDS )
set(yumi_startup_EXEC_DEPENDS )
set(yumi_startup_RUN_DEPENDS )
set(yumi_startup_TEST_DEPENDS )
set(yumi_startup_DOC_DEPENDS )
set(yumi_startup_URL_WEBSITE "")
set(yumi_startup_URL_BUGTRACKER "")
set(yumi_startup_URL_REPOSITORY "https://github.com/ethz-asl/yumi")
set(yumi_startup_DEPRECATED "")