set(_CATKIN_CURRENT_PACKAGE "libvisensor")
set(libvisensor_VERSION "1.1.0")
set(libvisensor_MAINTAINER "Pascal Gohl <pascal.gohl@mavt.ethz.ch>")
set(libvisensor_PACKAGE_FORMAT "1")
set(libvisensor_BUILD_DEPENDS "eigen")
set(libvisensor_BUILD_EXPORT_DEPENDS )
set(libvisensor_BUILDTOOL_DEPENDS "catkin")
set(libvisensor_BUILDTOOL_EXPORT_DEPENDS )
set(libvisensor_EXEC_DEPENDS )
set(libvisensor_RUN_DEPENDS )
set(libvisensor_TEST_DEPENDS )
set(libvisensor_DOC_DEPENDS )
set(libvisensor_URL_WEBSITE "http://www.skybotix.com")
set(libvisensor_URL_BUGTRACKER "")
set(libvisensor_URL_REPOSITORY "")
set(libvisensor_DEPRECATED "")