set(_CATKIN_CURRENT_PACKAGE "touch_custom_msgs")
set(touch_custom_msgs_VERSION "0.0.0")
set(touch_custom_msgs_MAINTAINER "xiaohulu1130 <xiaohulu1130@todo.todo>")
set(touch_custom_msgs_PACKAGE_FORMAT "2")
set(touch_custom_msgs_BUILD_DEPENDS "geometry_msgs" "message_generation" "message_runtime" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(touch_custom_msgs_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(touch_custom_msgs_BUILDTOOL_DEPENDS "catkin")
set(touch_custom_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(touch_custom_msgs_EXEC_DEPENDS "geometry_msgs" "message_runtime" "message_generation" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(touch_custom_msgs_RUN_DEPENDS "geometry_msgs" "message_runtime" "message_generation" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(touch_custom_msgs_TEST_DEPENDS )
set(touch_custom_msgs_DOC_DEPENDS )
set(touch_custom_msgs_URL_WEBSITE "")
set(touch_custom_msgs_URL_BUGTRACKER "")
set(touch_custom_msgs_URL_REPOSITORY "")
set(touch_custom_msgs_DEPRECATED "")